LOG.PATH=inputs/HealthApp.log
LOG.CHARSET=UTF-8
LOG.TIMESTAMP.REGEX_PATTERN=(?<year>\\d{4})(?<month>\\d{2})(?<day>\\d{2})-(?<hour>\\d{1,2}):(?<minute>\\d{1,2}):(?<seconds>\\d{1,2}):(?<millis>\\d{1,3})
LOG.TIMESTAMP.PATTERN=
ALGO.MAX_WINDOW_SIZE=50
ALGO.MAX_WINDOW_TS_SPAN=3
ALGO.MIN_OCCURRENCE=600
ALGO.MIN_SUPPORT=0.98
ALGO.GROWTH_FACTOR=0.02