LOG.PATH=inputs/openstack.log
LOG.CHARSET=UTF-8
LOG.TIMESTAMP.PATTERN=yyyy-MM-dd HH:mm:ss.SSS
LOG.TIMESTAMP.REGEX_PATTERN=
ALGO.MAX_WINDOW_SIZE=50
ALGO.MAX_WINDOW_TS_SPAN=3
ALGO.MIN_OCCURRENCE=60
ALGO.MIN_SUPPORT=0.95
ALGO.GROWTH_FACTOR=0.02