LOG.PATH=inputs/windows.log
LOG.CHARSET=UTF-8
LOG.TIMESTAMP.PATTERN=yyyy/MM/dd HH:mm:ss
LOG.TIMESTAMP.REGEX_PATTERN=
ALGO.MAX_WINDOW_SIZE=50
ALGO.MAX_WINDOW_TS_SPAN=3
ALGO.MIN_OCCURRENCE=50
ALGO.MIN_SUPPORT=0.9
ALGO.GROWTH_FACTOR=0.01